# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Tea"
license = "MIT"
licenselink = "https://github.com/Selbosh/hugo-tea/blob/master/LICENSE.md"
description = "A minimalist, single-column blog theme"
homepage = "https://github.com/Selbosh/hugo-tea"
tags = ["blog", "minimal", "minimalist", "light", "white"]
features = ["blog", "minimal"]
min_version = "0.79.1"

[author]
  name = "David Selby"
  homepage = "https://selbydavid.com"
